import type { GeneratedCodeType } from '../types'
import { KEY_SEPARATOR } from './DependencyTracker'

type MappedDependencyType = GeneratedCodeType | 'fragment-name'

export type MappedDependency = {
  /**
   * The dependency type.
   */
  type: MappedDependencyType

  /**
   * The name of the dependency.
   *
   * Can either be the name of a generated type or the name of a GraphQL fragment.
   */
  value: string
}

/**
 * Map the given dependency keys to MappedDependency objects.
 *
 * @param dependencies - The dependency keys (as generated by the DependencyTracker).
 *
 * @returns The mapped dependencies.
 */
function mapDependencies(dependencies?: string[]): MappedDependency[] {
  if (!dependencies) {
    return []
  }
  return dependencies.map((dependency) => {
    const [type, value] = dependency.split(KEY_SEPARATOR)
    return {
      type: type as MappedDependencyType,
      value: value || '',
    }
  })
}

/**
 * Provides dependency awarness.
 */
export class DependencyAware {
  /**
   * The mapped dependencies.
   *
   * This is generated the first time one of the class methods is called.
   */
  private mappedDependencies: MappedDependency[] | null = null

  constructor(public readonly dependencyStrings: string[]) {}

  /**
   * Get the mapped dependencies.
   *
   * @param type - Optionally filter for the given dependency type.
   *
   * @returns The mapped dependencies.
   */
  public getDependencies(
    type?: MappedDependencyType,
  ): readonly MappedDependency[] {
    if (this.mappedDependencies === null) {
      this.mappedDependencies = mapDependencies(this.dependencyStrings)
    }

    if (type) {
      return this.mappedDependencies.filter((v) => v.type === type)
    }

    return this.mappedDependencies
  }

  /**
   * Returns the GraphQL name of all fragment dependencies.
   *
   * @returns The name of fragment dependencies.
   */
  public getGraphQLFragmentDependencies(): string[] {
    return this.getDependencies('fragment-name').map((v) => v.value)
  }

  /**
   * Returns the TypeScript name of enum dependencies.
   *
   * @returns The name of enum dependencies.
   */
  public getTypeScriptEnumDependencies(): string[] {
    return this.getDependencies('enum').map((v) => v.value)
  }
}
