name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: unbuild
        run: npm run build

      - name: Typecheck
        run: npm run typecheck

      - name: ESlint
        run: npm run lint

      - name: Prettier
        run: npm run prettier

      - name: Vitest
        run: npm run test
