name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: unbuild
        run: |
          npm run build

      - name: Typecheck
        run: |
          npm run typecheck

      - name: ESlint
        run: |
          npm run lint

      - name: Prettier
        run: |
          npm run prettier

      - name: Vitest
        run: |
          npm run test
